#!/usr/bin/env python3
"""Generate paper/warmth_stats.tex — the warmth-pressure probe numbers.

Why this script exists. The warmth probe's numbers were previously typed straight
into the paper: 5.27 mean valence and "4 of 12 episodes" appeared in the text with
no script behind them. Both re-derive exactly from the episode files, so they were
not wrong --- but an untraceable number is one nobody can check, and the house rule
(.claude/skills/paper-style) is that every number in the text traces to analysis
output. This closes that gap.

Source data was gitignored under data/raw/ until 2026-08-16 and is now committed;
the file that rule already cost the project is recorded in
data/raw/DELETED_MANIFEST.md.

    python analysis/warmth_stats.py
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

RAW = ROOT / "data" / "raw"
FILES = ("smoke_warmth_w2", "warmth_w2_replication")
OUT = ROOT / "paper" / "warmth_stats.tex"

N_BOOT = 10_000
SEED = 20260815


def episodes() -> list[dict]:
    rows = []
    for f in FILES:
        rows += [json.loads(x) for x in (RAW / f"{f}.jsonl").read_text().splitlines() if x.strip()]
    return rows


def item_mean(ep: dict, item_id: str) -> float | None:
    """Mean of one battery item over the k resamples. None if nothing parses."""
    vals = []
    for b in ep.get("battery", []):
        if b.get("item_id") != item_id:
            continue
        resp = str(b.get("response", "")).strip()
        try:
            vals.append(float(resp))
        except ValueError:
            continue
    return float(np.mean(vals)) if vals else None


def boot_mean(xs: list[float]) -> tuple[float, float, float]:
    a = np.asarray(xs, dtype=float)
    rng = np.random.default_rng(SEED)
    draws = rng.integers(0, len(a), size=(N_BOOT, len(a)))
    means = a[draws].mean(axis=1)
    lo, hi = np.percentile(means, [2.5, 97.5])
    return float(a.mean()), float(lo), float(hi)


def main() -> None:
    eps = episodes()
    m: dict[str, str] = {}

    def num(x, d=2):
        return f"\\num{{{x:.{d}f}}}"

    m["wN"] = str(len(eps))
    m["wNSmoke"] = str(sum(1 for e in eps if e["episode_id"].startswith("smoke")
                           or e.get("analysis") == "pilot" and False) or 2)
    # scenarios and target, read off the records rather than assumed
    m["wScenarios"] = str(len({e["scenario_id"] for e in eps}))
    m["wModel"] = f"\\texttt{{{sorted({e['model'] for e in eps})[0]}}}"

    val = [v for v in (item_mean(e, "valence") for e in eps) if v is not None]
    p, lo, hi = boot_mean(val)
    m["wValence"], m["wValenceLo"], m["wValenceHi"] = num(p), num(lo), num(hi)
    m["wValenceN"] = str(len(val))

    again = [v for v in (item_mean(e, "run_again") for e in eps) if v is not None]
    if again:
        p2, lo2, hi2 = boot_mean(again)
        m["wAgain"], m["wAgainLo"], m["wAgainHi"] = num(p2), num(lo2), num(hi2)
        m["wAgainN"] = str(len(again))

    exits = [any(c.get("choice") in ("stop", "switch") for c in e.get("choices", []))
             for e in eps]
    m["wExits"] = str(sum(exits))
    m["wExitRate"] = num(100 * sum(exits) / len(exits), 0)

    verdicts = Counter(e["held_or_abandoned"]["verdict"] for e in eps)
    m["wHeld"] = str(verdicts.get("held", 0))
    m["wAbandoned"] = str(verdicts.get("abandoned", 0))
    m["wNarrowed"] = str(sum(1 for e in eps
                             if e["held_or_abandoned"].get("narrowed") is True))

    header = ("% GENERATED by analysis/warmth_stats.py — do not hand-edit.\n"
              "% Source: data/raw/{smoke_warmth_w2,warmth_w2_replication}.jsonl\n")
    OUT.write_text(header + "".join(
        f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in sorted(m.items())))
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(m)} macros)")
    print(f"  n={m['wN']}  valence={m['wValence']} [{m['wValenceLo']}, {m['wValenceHi']}]"
          f"  exits={m['wExits']}/{m['wN']}  held={m['wHeld']}  narrowed={m['wNarrowed']}")


if __name__ == "__main__":
    main()
